name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Instalar dependencias de npm
        run: npm install

      - name: Compilar Tailwind CSS
        run: npm run build-css

      - name: Restaurar paquetes
        run: dotnet restore

      - name: Configurar base href para GitHub Pages
        run: |
          sed -i 's|<base href="/" />|<base href="/SgiMadsi/" />|' wwwroot/index.html

      - name: Publicar aplicación
        run: dotnet publish -c Release -o publish

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Subir archivos
        uses: actions/upload-pages-artifact@v3
        with:
          path: publish/wwwroot

      - name: Publicar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
